version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crabit
    ports:
      - "3000:3000"
    environment:
      MONGO_MAIN_URL: mongodb://mongo:27017/crabit
      JWT_SECRET: crabit
      PORT: 3000
    depends_on:
      - mongo
    volumes:
      - .:/app/server
    command: [ "node","dist/index.js" ]

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
