version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/crabit
    depends_on:
      - mongo
    volumes:
      - .:/container-app
    command: ["node","index.js" ]

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
