name: Run Tests on Push to Test Branch

on:
  push:
    branches:
      - test

jobs:
  run-tests-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          echo MONGO_MAIN_URL=${{ secrets.MONGO_MAIN_URL }} >> server/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> server/.env
          echo PORT=${{ secrets.PORT }} >> server/.env

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run create-user integration test
        run: |
          cd server
          npm run test-create-user

      - name: Run get-user integration test
        run: |
          cd server
          npm run test-get-user

      - name: Run login-user integration test
        run: |
          cd server
          npm run test-login-user

      - name: Run unit tests
        run: |
          cd server
          npm run test

      - name: Merge to main
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge test
          git push origin main
